# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - '*'
  schedule:
      - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install-full-vim:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install vim
      run: |
        cd $GITHUB_WORKSPACE/vim
        ./install.sh
        
  test-configures:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install basic software
      run: |
        cd $GITHUB_WORKSPACE/
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update && sudo apt-get install -y \
                                            curl \
                                            git \
                                            fish \
                                            fzf \
                                            tmux \
                                            awesome

    - name: Run configs
      run: |
        cd $GITHUB_WORKSPACE/
        ./configure-fish.sh
        ./configure-tmux.sh
        ./configure-spacevim.sh
        ./configure-awesome.sh


