# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - '*'
  schedule:
      - cron: '0 0 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install-full-vim:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install vim
      run: |
        cd $GITHUB_WORKSPACE/vim
        ./install.sh
        
  test-configures:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install basic software
      run: |
        cd $GITHUB_WORKSPACE/
        export DEBIAN_FRONTEND=noninteractive
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt-get update && sudo apt-get install -y \
                                            curl \
                                            git \
                                            fish \
                                            fzf \
                                            tmux \
                                            awesome \
                                            emacs27

    - name: Run configure-fish
      run: |
        cd $GITHUB_WORKSPACE/
        sudo ./configure-fish.sh

    - name: Run configure-tmux
      run: |
        cd $GITHUB_WORKSPACE/
        sudo ./configure-tmux.sh

    - name: Run configure-spacevim
      run: |
        cd $GITHUB_WORKSPACE/
        sudo ./configure-spacevim.sh

    - name: Run configure-awesome
      run: |
        cd $GITHUB_WORKSPACE/
        sudo ./configure-awesome.sh

    - name: Run configure-emacs
      run: |
           cd $GITHUB_WORKSPACE
           sudo ./configure-emacs.sh
    - name: Run xfce
      run: |
          cd $GITHUB_WORKSPACE
          sudo ./configure-xfce4
